default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: english_memo
  host: localhost
  port: 3306
  username: root 
  password: violet

development:
  <<: *default

test:
  <<: *default
  database: foobar_test

staging:
  <<: *default

production:
  <<: *default

